/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Agent */

#ifndef _Included_Agent
#define _Included_Agent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Agent
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Agent_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     Agent
 * Method:    GetLocalTime
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Agent_GetLocalTime
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Agent
 * Method:    GetLocalOs
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Agent_GetLocalOs
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
